language: go
dist: xenial
go:
  - '1.12.x'

env:
  - GO111MODULE=off

stages:
  - name: test
  - name: release
    if: tag IS present

go_import_path: github.com/src-d/k8s-pod-headless-service-operator

jobs:
  include:
    - name: 'Unit tests'
      stage: test
      script: make test
    - name: 'Yaml tests'
      stage: test
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y yamllint
      script:
        - find -regex '.*\.ya?ml' -not -path "./vendor/*" -not -path "./.travis.yml" | xargs -n1 yamllint
    - name: 'Check deps'
      install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      script:
        - dep ensure -v
        - make no-changes-in-commit
        - make build
        - make no-changes-in-commit
    - name: 'Push image to Docker Hub'
      stage: release
      script:
        - PKG_OS=linux make packages
        - DOCKER_PUSH_LATEST=true make docker-push
